# Generated by Django 5.2.4 on 2025-10-05 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_application'),
        ('jobboard', '0004_jobapplication_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='JobApplication',
        ),
    ]
