# Generated by Django 5.2.4 on 2025-11-01 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_bio_user_phone_user_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
