# Generated by Django 5.2.4 on 2025-08-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0002_joblisting_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='applications_pdfs/'),
        ),
    ]
