# Generated by Django 5.2.4 on 2025-10-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0004_jobapplication_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Hired', 'Hired'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
